# Generated by Django 5.0.1 on 2025-05-01 15:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory_management', '0001_initial'),
        ('procurement_system', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Return',
            fields=[
                ('return_id', models.AutoField(primary_key=True, serialize=False)),
                ('return_date', models.DateField()),
                ('reason', models.TextField()),
                ('origin_transaction_id', models.IntegerField()),
                ('return_quantity', models.IntegerField()),
                ('status', models.CharField(max_length=100)),
                ('return_type', models.CharField(max_length=100)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory_management.item')),
            ],
            options={
                'db_table': 'returns',
            },
        ),
        migrations.CreateModel(
            name='ShipmentTracking',
            fields=[
                ('shipment_id', models.AutoField(primary_key=True, serialize=False)),
                ('shipment_date', models.DateField()),
                ('estimated_arrival', models.DateField()),
                ('tracking_number', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=100)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='procurement_system.supplier')),
            ],
            options={
                'db_table': 'shipment_tracking',
            },
        ),
        migrations.CreateModel(
            name='ShipmentItem',
            fields=[
                ('shipment_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory_management.item')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shipment_tracking.shipmenttracking')),
            ],
            options={
                'db_table': 'shipment_items',
            },
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('transfer_id', models.AutoField(primary_key=True, serialize=False)),
                ('transfer_date', models.DateField()),
                ('status', models.CharField(max_length=100)),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_approved_by', to=settings.AUTH_USER_MODEL)),
                ('destination_warehouse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destination_warehouse', to='inventory_management.warehouse')),
                ('origin_warehouse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='origin_warehouse', to='inventory_management.warehouse')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_requested_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'transfers',
            },
        ),
        migrations.CreateModel(
            name='TransferItem',
            fields=[
                ('transfer_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory_management.item')),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shipment_tracking.transfer')),
            ],
            options={
                'db_table': 'transfer_items',
            },
        ),
    ]
