# Generated by Django 5.0.1 on 2025-05-01 15:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('inventory_id', models.AutoField(primary_key=True, serialize=False)),
                ('available_quantity', models.IntegerField()),
                ('minimum_quantity', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'inventory',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('unit', models.CharField(default='unit', max_length=50)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'db_table': 'items',
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('warehouse_id', models.AutoField(primary_key=True, serialize=False)),
                ('warehouse_name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('capacity', models.IntegerField()),
            ],
            options={
                'db_table': 'warehouses',
            },
        ),
        migrations.CreateModel(
            name='InventoryAudit',
            fields=[
                ('audit_id', models.AutoField(primary_key=True, serialize=False)),
                ('audit_date', models.DateField()),
                ('remarks', models.TextField(blank=True, null=True)),
                ('audited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory_management.inventory')),
            ],
            options={
                'db_table': 'inventory_audit',
            },
        ),
        migrations.AddField(
            model_name='inventory',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory_management.item'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='warehouse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory_management.warehouse'),
        ),
        migrations.CreateModel(
            name='Distribution',
            fields=[
                ('distribution_id', models.AutoField(primary_key=True, serialize=False)),
                ('distribution_date', models.DateField()),
                ('quantity', models.IntegerField()),
                ('status', models.CharField(max_length=100)),
                ('distributed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distribution_made', to=settings.AUTH_USER_MODEL)),
                ('distributed_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distribution_received', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory_management.item')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory_management.warehouse')),
            ],
            options={
                'db_table': 'distributions',
            },
        ),
    ]
