# Generated by Django 5.0.2 on 2025-05-09 22:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0004_warehouse_created_at_warehouse_is_active_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='distribution',
            name='distributed_by',
        ),
        migrations.RemoveField(
            model_name='distribution',
            name='distributed_to',
        ),
        migrations.RemoveField(
            model_name='distribution',
            name='distribution_date',
        ),
        migrations.RemoveField(
            model_name='distribution',
            name='item',
        ),
        migrations.RemoveField(
            model_name='distribution',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='distribution',
            name='warehouse',
        ),
        migrations.AddField(
            model_name='distribution',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='distribution',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_distributions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='distribution',
            name='destination_warehouse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destination_distributions', to='inventory_management.warehouse'),
        ),
        migrations.AddField(
            model_name='distribution',
            name='estimated_delivery',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='distribution',
            name='source_warehouse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_distributions', to='inventory_management.warehouse'),
        ),
        migrations.AlterField(
            model_name='distribution',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_transit', 'In Transit'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='DistributionItem',
            fields=[
                ('distribution_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('distribution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory_management.distribution')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory_management.item')),
            ],
            options={
                'db_table': 'distribution_items',
            },
        ),
    ]
