# Generated by Django 5.0.2 on 2025-05-10 17:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0005_remove_distribution_distributed_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory_management.category')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory_management.warehouse')),
            ],
            options={
                'db_table': 'warehouse_categories',
                'unique_together': {('warehouse', 'category')},
            },
        ),
        migrations.AddField(
            model_name='warehouse',
            name='categories',
            field=models.ManyToManyField(related_name='warehouses', through='inventory_management.WarehouseCategory', to='inventory_management.category'),
        ),
    ]
