# Generated by Django 5.0.1 on 2025-05-01 15:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('purchase_id', models.AutoField(primary_key=True, serialize=False)),
                ('purchase_date', models.DateField()),
                ('status', models.CharField(max_length=100)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'db_table': 'purchases',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('supplier_id', models.AutoField(primary_key=True, serialize=False)),
                ('supplier_name', models.CharField(max_length=255)),
                ('contact_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'suppliers',
            },
        ),
        migrations.CreateModel(
            name='Procurement',
            fields=[
                ('procurement_id', models.AutoField(primary_key=True, serialize=False)),
                ('request_date', models.DateField()),
                ('required_by', models.DateField()),
                ('status', models.CharField(max_length=100)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurement_approved_by', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procurement_requested_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'procurement',
            },
        ),
        migrations.CreateModel(
            name='ProcurementItem',
            fields=[
                ('procurement_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('requested_quantity', models.IntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory_management.item')),
                ('procurement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='procurement_system.procurement')),
            ],
            options={
                'db_table': 'procurement_items',
            },
        ),
        migrations.CreateModel(
            name='PurchaseItem',
            fields=[
                ('purchase_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('ordered_quantity', models.IntegerField()),
                ('received_quantity', models.IntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory_management.item')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='procurement_system.purchase')),
            ],
            options={
                'db_table': 'purchase_items',
            },
        ),
        migrations.AddField(
            model_name='purchase',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='procurement_system.supplier'),
        ),
    ]
