# Generated by Django 5.0.2 on 2025-05-12 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement_system', '0002_supplier_city_supplier_country_supplier_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procurementitem',
            name='procurement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='procurement_system.procurement'),
        ),
    ]
