# Generated by Django 5.0.2 on 2025-05-12 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement_system', '0003_alter_procurementitem_procurement'),
    ]

    operations = [
        migrations.AddField(
            model_name='procurement',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
