# Generated by Django 5.0.1 on 2025-05-01 15:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceHistory',
            fields=[
                ('maintenance_id', models.AutoField(primary_key=True, serialize=False)),
                ('maintenance_date', models.DateField()),
                ('performed_by', models.CharField(max_length=255)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory_management.item')),
            ],
            options={
                'db_table': 'maintenance_history',
            },
        ),
        migrations.CreateModel(
            name='ReportItem',
            fields=[
                ('report_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('report_type', models.CharField(max_length=255)),
                ('report_date', models.DateField()),
                ('description', models.TextField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory_management.item')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'report_items',
            },
        ),
    ]
