# Generated by Django 5.0.1 on 2025-05-01 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DateDim',
            fields=[
                ('date_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(unique=True)),
                ('day', models.IntegerField()),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('quarter', models.IntegerField()),
            ],
            options={
                'db_table': 'date_dim',
            },
        ),
        migrations.CreateModel(
            name='PromotionDim',
            fields=[
                ('promotion_id', models.AutoField(primary_key=True, serialize=False)),
                ('promotion_name', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('discount_type', models.CharField(max_length=100)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'promotion_dim',
            },
        ),
        migrations.CreateModel(
            name='StoreDim',
            fields=[
                ('store_id', models.AutoField(primary_key=True, serialize=False)),
                ('store_name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'store_dim',
            },
        ),
    ]
